#!/usr/bin/env python3
"""Thêm điểm đến Sa Pa: Fansipan, bản làng, ruộng bậc thang, thác, chợ, ẩm thực vùng cao.
Địa điểm là nơi có thật nhưng toạ độ, giá, giờ mở cửa là ƯỚC LƯỢNG (cờ "approx"), khách sạn là dữ liệu MẪU. Chạy lại được, không trùng.
Chạy: python3 scripts/add-sapa.py"""
import sys, pathlib
sys.path.insert(0, str(pathlib.Path(__file__).resolve().parent))
from _dest import make_place, run, ALL
CITY = "Sa Pa"
place = make_place(CITY)
H = lambda *a: list(a)
NEW = [
 place("fansipan", "Đỉnh Fansipan (cáp treo)", "park", "morning", 22.3033, 103.7750, 240, 800000, "07:30", "17:30", "mountain",
   H("Đi cáp treo từ ga Sa Pa lên gần đỉnh rồi leo bậc thang, giá khoảng 750.000–950.000 đ khứ hồi (ước lượng, kiểm tra lại)", "Đi sáng sớm cho đỡ mây mù, mang áo ấm và áo mưa", "Trên đỉnh lạnh và gió, mặc nhiều lớp"),
   "Đỉnh cao nhất Đông Dương (3.143 m), được gọi là nóc nhà Đông Dương. Hiện có tuyến cáp treo dài, tuyến tàu leo núi Mường Hoa và hệ thống bậc thang lên tới đỉnh.",
   "Ga cáp treo Fansipan, thị xã Sa Pa", 3, elderly=False),
 place("ban-cat-cat", "Bản Cát Cát", "culture", "morning", 22.3290, 103.8300, 120, 70000, "07:00", "17:30", "field",
   H("Bản của người H'Mông với nhà gỗ, thác nhỏ, xưởng dệt thổ cẩm", "Giá vé khoảng 70.000 đ (ước lượng), kiểm tra lại", "Đường xuống dốc bậc thang, mang giày bám tốt"),
   "Bản làng người H'Mông cách trung tâm khoảng 2 km, có nghề dệt thổ cẩm, nhuộm chàm, thác Tiên Sa và những nếp nhà gỗ ven suối.",
   "Xã San Sả Hồ, cách trung tâm khoảng 2 km", 2),
 place("thung-lung-muong-hoa", "Thung lũng Mường Hoa (ruộng bậc thang)", "park", "afternoon", 22.3000, 103.8700, 150, 0, "00:00", "23:59", "field",
   H("Ruộng bậc thang đẹp nhất mùa lúa chín (khoảng tháng 9–10) và mùa nước đổ (tháng 5–6)", "Có thể đi bộ trekking nhẹ qua các bản Lao Chải, Tả Van", "Mùa mưa đường trơn, nên thuê xe và hướng dẫn viên"),
   "Thung lũng với những thửa ruộng bậc thang uốn quanh sườn núi và dòng suối Mường Hoa, nơi sinh sống của người H'Mông, Dao, Giáy, tạo nên bức tranh đẹp nhất của Sa Pa.",
   "Xã Mường Hoa, cách trung tâm khoảng 8 km", 3, elderly=False),
 place("ban-ta-van", "Bản Tả Van", "culture", "afternoon", 22.2960, 103.8780, 120, 0, "00:00", "23:59", "field",
   H("Làng người Giáy bên suối, nhà sàn, có thể ở homestay", "Có thể đi bộ từ Lao Chải, khoảng 3 đến 4 giờ", "Thường tính phí gửi xe hoặc hướng dẫn nếu đi theo tour"),
   "Bản làng của người Giáy nằm sâu trong thung lũng, nhà sàn, ruộng lúa và dòng suối trong, yên tĩnh và đậm sắc văn hoá dân tộc.",
   "Xã Tả Van, cách trung tâm khoảng 10 km", 3),
 place("thac-bac", "Thác Bạc", "park", "morning", 22.3640, 103.7900, 75, 20000, "07:00", "17:30", "mountain",
   H("Thác cao khoảng 100 m, ngay đường đi Cổng Trời, giá vé khoảng 20.000 đ (ước lượng)", "Mùa mưa thác lớn, hơi nước nhiều", "Có bậc thang lên các tầng thác"),
   "Thác nước trắng xoá đổ từ độ cao hàng chục mét giữa núi rừng Hoàng Liên Sơn, cách trung tâm thị xã khoảng 12 km.",
   "Quốc lộ 4D, cách trung tâm khoảng 12 km", 2),
 place("cong-troi-o-quy-ho", "Đèo Ô Quy Hồ và Cổng Trời", "checkin", "afternoon", 22.3586, 103.7766, 60, 0, "00:00", "23:59", "mountain",
   H("Đèo cao nhất Việt Nam, ngắm mây và dãy Hoàng Liên Sơn", "Thường có sương mù, mang áo ấm", "Chụp ảnh buổi sáng hoặc chiều muộn"),
   "Một trong tứ đại đèo của miền Bắc, nối Lào Cai với Lai Châu, nổi tiếng với cảnh mây trôi dưới chân và dãy núi trùng điệp.",
   "Đèo Ô Quy Hồ, cách trung tâm khoảng 15 km", 1),
 place("nui-ham-rong", "Núi Hàm Rồng", "park", "morning", 22.3330, 103.8420, 120, 70000, "07:00", "17:00", "mountain",
   H("Vườn hoa, vườn lan, sân mây nhìn ra thị xã Sa Pa", "Giá vé khoảng 70.000 đ, kiểm tra lại", "Có nhiều bậc thang, đi sáng cho đỡ mây"),
   "Ngọn núi nhỏ ngay sát thị xã với vườn hoa, vườn lan, cổng trời mây và nhiều điểm ngắm toàn cảnh thung lũng, hợp đi nhẹ nhàng.",
   "Phố Phan Xi Păng, thị xã Sa Pa", 2),
 place("nha-tho-da-sapa", "Nhà thờ đá Sa Pa", "checkin", "evening", 22.3360, 103.8430, 30, 0, "06:00", "21:00", "temple",
   H("Nhà thờ đá xây năm 1895 theo kiến trúc Pháp, ngay cạnh quảng trường trung tâm", "Tối có đèn và nhạc đường phố", "Giữ yên lặng khi vào trong"),
   "Nhà thờ đá cổ từ thời Pháp thuộc, kiến trúc Gothic, là biểu tượng trung tâm của thị xã Sa Pa, nơi tụ họp của dân và du khách vào buổi tối.",
   "Quảng trường trung tâm Sa Pa", 0),
 place("cho-sapa", "Chợ Sa Pa", "checkin", "morning", 22.3390, 103.8440, 60, 0, "05:00", "19:00", "market",
   H("Mua thổ cẩm, đặc sản, rau rừng, thịt hun khói", "Giữ kỹ đồ cá nhân, trả giá nhẹ", "Phiên chợ nhiều màu sắc vào cuối tuần"),
   "Chợ trung tâm với nhiều gian hàng thổ cẩm, rau quả, mật ong, thịt gác bếp và các sản phẩm của đồng bào dân tộc.",
   "Đường Cầu Mây, thị xã Sa Pa", 1),
 place("cho-dem-sapa", "Chợ đêm và phố ẩm thực Sa Pa", "food", "evening", 22.3365, 103.8440, 90, 120000, "17:00", "23:00", "market",
   H("Thịt nướng, trứng nướng, sữa đậu nành nóng, bánh bao, ngô nướng", "Buổi tối rất lạnh, mang áo ấm", "Giữ kỹ đồ cá nhân"),
   "Phố chợ đêm quanh nhà thờ đá với hàng quán nướng, xiên nóng và đồ ăn vặt, là cách ngắm đêm Sa Pa quen thuộc.",
   "Khu vực nhà thờ đá, thị xã Sa Pa", 1, meal="dinner", desc="Chợ đêm và phố nướng.", dishes=["Thịt nướng", "Trứng nướng", "Sữa đậu nành"]),
 place("lau-ca-tam-sapa", "Lẩu cá tầm và cá hồi Sa Pa", "food", "evening", 22.3355, 103.8410, 90, 280000, "10:30", "21:30", "food",
   H("Cá tầm, cá hồi nuôi vùng nước lạnh, lẩu và nướng", "Nên đi nhóm 3 đến 4 người", "Địa chỉ chưa xác minh, tra trên Google Maps"),
   "Cá hồi và cá tầm nuôi trong nước suối lạnh là đặc sản vùng cao Sa Pa, thường ăn lẩu, nướng hoặc làm gỏi.",
   "Khu trung tâm (chưa xác minh số nhà)", 0, meal="dinner", desc="Quán lẩu cá tầm, cá hồi.", dishes=["Lẩu cá tầm", "Cá hồi nướng", "Gỏi cá hồi"], aud=["nhom_ban", "gia_dinh", "cap_doi"]),
 place("thang-co-sapa", "Thắng cố và món người H'Mông", "food", "midday", 22.3380, 103.8430, 50, 80000, "09:00", "20:00", "food",
   H("Thắng cố là món ăn lạ miệng, nên hỏi nhân viên trước nếu lần đầu thử", "Có thể gọi thêm thịt lợn cắp nách, rau cải mèo, xôi ngũ sắc", "Địa chỉ chưa xác minh, tra trên Google Maps"),
   "Thắng cố là món truyền thống của người H'Mông, thịt và nội tạng ngựa hoặc bò hầm cùng thảo quả. Quán Sa Pa còn có thịt lợn cắp nách, xôi ngũ sắc và rau rừng.",
   "Khu trung tâm (chưa xác minh số nhà)", 0, meal="lunch", desc="Quán món dân tộc.", dishes=["Thắng cố", "Thịt lợn cắp nách", "Xôi ngũ sắc"], kids=False),
 place("com-lam-ga-nuong-sapa", "Cơm lam và gà nướng bản", "food", "midday", 22.3350, 103.8440, 60, 120000, "10:00", "21:00", "food",
   H("Cơm lam nướng trong ống tre, gà ta nướng mọi, rau bản", "Quán ăn đông giờ trưa", "Địa chỉ chưa xác minh, tra trên Google Maps"),
   "Cơm lam, gà nướng và rau rừng là bữa ăn quen thuộc của vùng núi, ăn nóng giữa tiết trời se lạnh.",
   "Khu trung tâm (chưa xác minh số nhà)", 0, meal="lunch", desc="Quán cơm lam và gà nướng.", dishes=["Cơm lam", "Gà nướng", "Rau rừng"]),
 place("ban-lao-chai", "Bản Lao Chải", "culture", "morning", 22.3150, 103.8650, 120, 0, "00:00", "23:59", "field",
   H("Bản của người H'Mông, đi bộ trekking nhẹ từ Mường Hoa", "Có thể thuê hướng dẫn viên người địa phương", "Mùa mưa đường trơn"),
   "Một trong những bản làng nổi tiếng nhất ở Sa Pa, nhà gỗ nằm giữa ruộng bậc thang, là điểm xuất phát quen thuộc cho các tuyến trekking tới Tả Van.",
   "Xã Hoàng Liên, cách trung tâm khoảng 7 km", 3, elderly=False),
 place("ban-ta-phin", "Bản Tả Phìn (người Dao đỏ)", "culture", "afternoon", 22.3700, 103.9000, 120, 0, "00:00", "23:59", "field",
   H("Bản người Dao đỏ nổi tiếng với nghề tắm thuốc lá và thổ cẩm", "Có thể trải nghiệm tắm lá thuốc, giá hỏi tại chỗ", "Xa hơn các bản khác, nên đi buổi sáng"),
   "Bản làng người Dao đỏ có hang động Tả Phìn, nghề thêu thổ cẩm và tắm lá thuốc là nét văn hoá đặc trưng thu hút nhiều du khách.",
   "Xã Tả Phìn, cách trung tâm khoảng 12 km", 2),
 place("cf-may-sapa", "Quán cà phê ngắm mây Sa Pa (mẫu)", "cafe", "afternoon", 22.3345, 103.8440, 75, 60000, "07:00", "22:00", "cafe",
   H("Ngồi ban công ngắm thung lũng và mây, mang áo ấm", "Quán mẫu, chưa phải quán thật"),
   "Cà phê ngắm mây là trải nghiệm quen thuộc ở Sa Pa, vừa uống cà phê nóng vừa nhìn sương trôi qua thung lũng.",
   "Khu trung tâm (quán mẫu)", 0, desc="Quán cà phê ngắm mây.", dishes=["Cà phê nóng", "Trà ấm", "Bánh nướng"]),
 place("cf-lo-suoi-sapa", "Quán cà phê lò sưởi (mẫu)", "cafe", "evening", 22.3365, 103.8430, 75, 65000, "07:00", "22:30", "cafe",
   H("Ngồi cạnh lò sưởi, uống trà gừng hoặc rượu táo mèo", "Quán mẫu, chưa phải quán thật"),
   "Quán có lò sưởi và đèn vàng ấm là nơi nghỉ chân quen thuộc của du khách vào buổi tối lạnh.",
   "Khu trung tâm (quán mẫu)", 0, desc="Quán cà phê lò sưởi.", dishes=["Trà gừng", "Táo mèo", "Cà phê"]),
]
HOTELS = [
 ("sp-hostel", "hostel-bien", "Hostel gần nhà thờ đá Sa Pa (mẫu)", "Trung tâm", 200000, 22.3360, 103.8430, "Hostel nhỏ gần quảng trường, phù hợp đi tiết kiệm.", ["Wifi", "Bếp chung"]),
 ("sp-homestay", "homestay", "Homestay bản làng (mẫu)", "Bản Cát Cát", 350000, 22.3300, 103.8310, "Homestay nhà gỗ trong bản, có bữa tối cùng chủ nhà.", ["Wifi", "Ăn sáng"]),
 ("sp-3sao", "3sao-tt", "Khách sạn 3 sao trung tâm (mẫu)", "Trung tâm", 650000, 22.3370, 103.8440, "Khách sạn 3 sao gần chợ đêm, có lò sưởi.", ["Wifi", "Ăn sáng"]),
 ("sp-3sao-nui", "3sao-bien", "Khách sạn 3 sao view núi (mẫu)", "Trung tâm", 850000, 22.3350, 103.8420, "Khách sạn 3 sao có ban công nhìn núi Hoàng Liên Sơn.", ["Wifi", "Ăn sáng"]),
 ("sp-4sao", "4sao-tt", "Khách sạn 4 sao trung tâm (mẫu)", "Trung tâm", 1400000, 22.3360, 103.8450, "Khách sạn 4 sao có spa và nhà hàng.", ["Wifi", "Ăn sáng", "Spa"]),
 ("sp-4sao-thung-lung", "4sao-bien", "Khách sạn 4 sao nhìn thung lũng (mẫu)", "Thung lũng", 1700000, 22.3340, 103.8460, "Khách sạn 4 sao nhìn xuống thung lũng Mường Hoa.", ["Wifi", "Ăn sáng", "Spa"]),
 ("sp-resort", "resort-nhs", "Resort 5 sao trên đồi (mẫu)", "Ngoại thành", 3300000, 22.3200, 103.8500, "Resort 5 sao trên đồi, có spa, hồ bơi nóng và nhà hàng.", ["Wifi", "Ăn sáng", "Spa", "Hồ bơi nóng"]),
 ("sp-villa", "villa", "Villa gỗ có lò sưởi (mẫu)", "Thung lũng", 3600000, 22.3250, 103.8550, "Villa gỗ riêng có lò sưởi và sân vườn nhìn thung lũng.", ["Wifi", "Ăn sáng", "Lò sưởi", "Bếp"]),
]
run(CITY, NEW, HOTELS)
