#!/usr/bin/env python3
"""Thêm điểm đến Huế: di sản cố đô (Đại Nội, lăng tẩm, chùa Thiên Mụ), sông Hương, ẩm thực cung đình và quán ăn Huế.
Địa điểm là nơi có thật nhưng toạ độ, giá, giờ mở cửa là ƯỚC LƯỢNG (cờ "approx"), khách sạn là dữ liệu MẪU. Chạy lại được, không trùng.
Chạy: python3 scripts/add-hue.py"""
import sys, pathlib
sys.path.insert(0, str(pathlib.Path(__file__).resolve().parent))
from _dest import make_place, run, ALL
CITY = "Huế"
place = make_place(CITY)
H = lambda *a: list(a)
NEW = [
 place("dai-noi-hue", "Đại Nội Huế (Hoàng thành)", "culture", "morning", 16.4698, 107.5791, 150, 200000, "08:00", "17:30", "temple",
   H("Giá vé khoảng 200.000 đ người lớn, kiểm tra lại, có vé combo tham quan nhiều di tích", "Đi sáng sớm cho mát, nên thuê hướng dẫn viên hoặc audio guide", "Mang nón, nước, giày đi bộ vì khuôn viên rộng"),
   "Quần thể kinh thành triều Nguyễn (1802–1945), gồm Ngọ Môn, điện Thái Hoà, Tử Cấm Thành và Thế Miếu. Di sản được UNESCO công nhận, là điểm đến quan trọng nhất của cố đô.",
   "Đường 23 Tháng 8, phường Thuận Thành", 2),
 place("bao-tang-co-vat-cung-dinh", "Bảo tàng Cổ vật Cung đình Huế", "culture", "afternoon", 16.4660, 107.5800, 60, 150000, "08:00", "17:30", "museum",
   H("Giá vé là ước lượng, kiểm tra lại", "Trưng bày đồ ngự dụng, ngọc tỉ, đồ sứ, long bào triều Nguyễn", "Có mái che, hợp ngày nắng hoặc mưa"),
   "Bảo tàng trưng bày những cổ vật cung đình triều Nguyễn như áo long bào, đồ sứ ngự dụng, ngai vàng và nhiều đồ dùng sinh hoạt hoàng gia.",
   "3 Lê Trực", 1),
 place("lang-khai-dinh", "Lăng Khải Định", "culture", "morning", 16.3992, 107.5911, 75, 150000, "07:00", "17:30", "temple",
   H("Giá vé khoảng 150.000 đ, kiểm tra lại, thường mua combo ba lăng", "Kiến trúc pha trộn Đông – Tây, nhiều mảng khảm sành sứ rất tinh xảo", "Có nhiều bậc thang lên cung Thiên Định"),
   "Lăng vua Khải Định xây từ 1920 đến 1931, nhỏ nhưng cực kỳ công phu, pha kiến trúc Á – Âu với nội thất khảm sành sứ, thuỷ tinh, được xem là lăng độc đáo nhất.",
   "Thôn Chân Chữ, xã Thuỷ Bằng", 2, elderly=False),
 place("lang-minh-mang", "Lăng Minh Mạng", "culture", "morning", 16.3858, 107.5780, 90, 150000, "07:00", "17:30", "temple",
   H("Giá vé khoảng 150.000 đ, kiểm tra lại", "Kiến trúc hài hoà với hồ, đồi thông, trục thần đạo dài", "Hợp đi buổi sáng cho mát và đỡ đông"),
   "Lăng vua Minh Mạng xây theo trục đối xứng với hồ Tân Nguyệt, đình, điện, nhiều toà nhà trên triền đồi, là một trong những lăng tẩm đẹp nhất triều Nguyễn.",
   "Núi Cẩm Kê, xã Hương Thọ", 2),
 place("lang-tu-duc", "Lăng Tự Đức", "culture", "afternoon", 16.4348, 107.5656, 90, 150000, "07:00", "17:30", "temple",
   H("Giá vé khoảng 150.000 đ, kiểm tra lại", "Khuôn viên như một công viên với hồ, đình, rừng thông", "Đi chiều muộn, ánh sáng rất đẹp"),
   "Lăng vua Tự Đức, nơi vua vừa ở vừa làm việc khi còn sống, có hồ Lưu Khiêm, khiêm cung và cảnh quan yên tĩnh, là nơi nhiều người thích nhất khi đi lăng tẩm.",
   "Thôn Thượng Ba, phường Thuỷ Xuân", 1),
 place("chua-thien-mu", "Chùa Thiên Mụ", "culture", "afternoon", 16.4537, 107.5445, 60, 0, "07:00", "17:00", "temple",
   H("Vào cổng miễn phí, ăn mặc kín đáo, giữ yên lặng", "Tháp Phước Duyên bảy tầng nhìn ra sông Hương", "Đi chiều muộn để ngắm hoàng hôn trên sông"),
   "Chùa cổ trên đồi Hà Khê bên bờ sông Hương, xây từ năm 1601, biểu tượng của Huế với tháp Phước Duyên bảy tầng, được nhắc nhiều trong thơ ca.",
   "Kim Long, phường Kim Long", 1),
 place("cau-truong-tien", "Cầu Trường Tiền", "checkin", "evening", 16.4690, 107.5900, 45, 0, "00:00", "23:59", "bridge",
   H("Cầu thép đổi màu đèn buổi tối, chụp ảnh đẹp", "Ra bờ sông Hương đi dạo, ăn kem hoặc uống trà", "Cuối tuần có nhạc đường phố trên phố đi bộ"),
   "Cây cầu thép sáu nhịp bắc qua sông Hương, thiết kế bởi Gustave Eiffel, nổi tiếng với dàn đèn đổi màu vào buổi tối, là biểu tượng thành phố.",
   "Nối đường Lê Lợi và Trần Hưng Đạo", 1),
 place("song-huong-thuyen-rong", "Du thuyền sông Hương (thuyền rồng)", "park", "evening", 16.4680, 107.5880, 90, 150000, "17:00", "21:30", "boat",
   H("Nghe ca Huế trên thuyền, thả hoa đăng, giá tham khảo khoảng 150.000 đ/người hoặc thuê thuyền riêng", "Hỏi rõ giá trọn gói trước khi lên thuyền", "Mùa mưa nước lớn, thuyền có thể ngưng"),
   "Trải nghiệm đặc trưng của Huế: ngồi thuyền rồng trên sông Hương nghe ca Huế, thả hoa đăng, ngắm cầu Trường Tiền và phố đêm lên đèn.",
   "Bến thuyền Toà Khâm, đường Lê Lợi", 0, aud=ALL),
 place("cho-dong-ba", "Chợ Đông Ba", "checkin", "morning", 16.4730, 107.5865, 60, 0, "06:00", "19:00", "market",
   H("Chợ lâu đời nhất Huế, bán đặc sản, mè xửng, nón lá, tré, ruốc", "Tầng trệt bán đồ ăn, tầng trên bán vải và đồ lưu niệm", "Hỏi giá và trả giá nhẹ"),
   "Chợ lớn nhất Huế, hơn 100 năm tuổi, bán đặc sản địa phương, nón lá bài thơ, mè xửng, tré, nem lụi và nhiều món ăn vặt.",
   "Trần Hưng Đạo, phường Phú Hoà", 1),
 place("cau-ngoi-thanh-toan", "Cầu ngói Thanh Toàn", "culture", "morning", 16.4260, 107.6460, 60, 0, "00:00", "23:59", "bridge",
   H("Cầu ngói cổ giữa làng quê, đi xe máy hoặc taxi khoảng 8 km từ trung tâm", "Có quán nước, chụp ảnh đồng lúa", "Đường nhỏ, đi cẩn thận khi mưa"),
   "Cây cầu mái ngói có từ thế kỷ 18, do bà Trần Thị Đạo xây dựng, nằm giữa đồng lúa làng Thanh Toàn, là điểm đến yên bình ngoài phố.",
   "Xã Thuỷ Thanh, Hương Thuỷ", 2),
 place("doi-vong-canh", "Đồi Vọng Cảnh", "checkin", "evening", 16.4290, 107.5530, 60, 0, "00:00", "23:59", "mountain",
   H("Ngắm hoàng hôn trên sông Hương, nhìn xuống các khúc sông uốn lượn", "Đi buổi chiều, khoảng 5 km từ trung tâm", "Đường dốc, chú ý khi mưa"),
   "Ngọn đồi nhỏ nhìn xuống sông Hương và những khúc quanh yên bình, là điểm ngắm hoàng hôn quen thuộc, vua Tự Đức từng ngự lên ngắm cảnh.",
   "Phường Thuỷ Xuân", 2),
 place("bien-thuan-an", "Biển Thuận An", "beach", "afternoon", 16.5370, 107.6320, 120, 0, "00:00", "23:59", "beach",
   H("Bãi biển gần thành phố, khoảng 12 km, mùa hè nước êm", "Ít dịch vụ, mang nước và ô", "Mùa mưa bão sóng lớn, kiểm tra thời tiết"),
   "Bãi biển gần nhất của thành phố Huế với cát trắng, nước trong, gần cửa biển Thuận An và có nhiều quán hải sản.",
   "Xã Thuận An, cách trung tâm khoảng 12 km", 1),
 place("quoc-tu-giam-hue", "Văn Thánh và Quốc Tử Giám Huế", "culture", "afternoon", 16.4490, 107.5600, 45, 40000, "08:00", "17:30", "museum",
   H("Giá vé là ước lượng, kiểm tra lại", "Khuôn viên yên tĩnh, hợp đi nhẹ", "Kết hợp với chùa Thiên Mụ gần đó"),
   "Văn Thánh là nơi thờ Khổng Tử và các bậc hiền triết thời Nguyễn, khuôn viên rộng với cây xanh, đình, vườn, nằm bên bờ sông Hương.",
   "Đường Nguyễn Phúc Nguyên", 1),
 # ---- Quán ăn
 place("bun-bo-hue-ba-tuyet", "Bún bò Huế Bà Tuyết", "food", "midday", 16.4620, 107.5890, 45, 50000, "06:00", "13:00", "food",
   H("Bún bò Huế nước dùng đậm, thơm sả, giò heo, chả cua", "Giờ trưa đông, thường hết sớm, nên đi buổi sáng", "Địa chỉ ghi theo một số nguồn, kiểm tra lại"),
   "Bún bò Huế là món đặc trưng nhất của xứ Huế: sợi bún to, nước dùng nấu từ xương bò, sả, mắm ruốc, vị cay thơm, ăn kèm giò, chả và rau sống.",
   "47 Nguyễn Công Trứ (theo một số nguồn)", 0, meal="lunch", desc="Quán bún bò Huế quen thuộc.", dishes=["Bún bò Huế", "Giò heo", "Chả cua"]),
 place("banh-khoai-lac-thien", "Bánh khoái Lạc Thiện", "food", "midday", 16.4640, 107.5930, 50, 60000, "08:30", "20:30", "food",
   H("Bánh khoái giòn, nhân tôm thịt, ăn với nước lèo và rau sống", "Có thể gọi kèm nem lụi, bánh bèo, bánh nậm", "Địa chỉ ghi theo một số nguồn, kiểm tra lại"),
   "Bánh khoái là món bánh cung đình được người Huế yêu thích, vỏ giòn nhân tôm, thịt, giá, chấm nước lèo đậm đà.",
   "6 Đinh Tiên Hoàng (theo một số nguồn)", 0, meal="lunch", desc="Quán bánh khoái nổi tiếng.", dishes=["Bánh khoái", "Nem lụi", "Bánh bèo"]),
 place("com-hen-hue", "Cơm hến Huế", "food", "midday", 16.4590, 107.5810, 40, 25000, "06:00", "14:00", "food",
   H("Cơm hến vị cay, ăn với mè rang, ruốc, rau thơm", "Thường bán sáng và trưa, ăn nhanh", "Địa chỉ chưa xác minh, tra trên Google Maps"),
   "Cơm hến là món dân dã của Huế, hến xào với rau thơm, ruốc, tóp mỡ, ăn với cơm nguội, vị cay nồng khó quên.",
   "Khu vực Vỹ Dạ hoặc Kim Long (chưa xác minh số nhà)", 0, meal="lunch", desc="Quán cơm hến dân dã.", dishes=["Cơm hến", "Bánh bèo", "Bánh nậm"]),
 place("che-hem-hue", "Chè Hẻm", "cafe", "afternoon", 16.4620, 107.5870, 30, 20000, "13:00", "21:00", "food",
   H("Chè Huế nhiều loại: chè bắp, chè bột lọc, chè hạt sen, chè đậu ngự", "Món tráng miệng nhẹ buổi chiều", "Địa chỉ ghi theo một số nguồn, kiểm tra lại"),
   "Chè Huế nổi tiếng với hàng chục loại chè nhỏ, vị ngọt thanh, bày trong từng chén nhỏ, thường ăn kèm bữa chiều.",
   "29 Hùng Vương (theo một số nguồn)", 0, desc="Quán chè Huế quen thuộc.", dishes=["Chè bắp", "Chè hạt sen", "Chè bột lọc"]),
 place("nem-lui-hue", "Nem lụi Huế", "food", "evening", 16.4600, 107.5820, 60, 80000, "10:00", "21:30", "food",
   H("Nem lụi nướng sả, cuốn bánh tráng với rau sống, chấm tương đậu phộng", "Nên gọi kèm bánh bèo, bánh nậm", "Địa chỉ chưa xác minh, tra trên Google Maps"),
   "Nem lụi là món nem nướng sả đặc trưng của Huế, thịt heo xay nướng trên que sả, cuốn bánh tráng, chấm tương đậu phộng thơm béo.",
   "Phố trung tâm Huế (chưa xác minh số nhà)", 0, meal="dinner", desc="Quán nem lụi quen thuộc.", dishes=["Nem lụi", "Bánh bèo", "Bánh nậm"]),
 place("com-cung-dinh-hue", "Bữa cơm cung đình Huế", "food", "evening", 16.4620, 107.5700, 90, 400000, "11:00", "21:00", "food",
   H("Thực đơn cung đình nhiều món, trình bày tinh xảo, giá tham khảo khoảng 400.000 đ/người, nên đặt trước", "Có thể kèm biểu diễn nhã nhạc", "Hỏi giá trọn gói và đặt trước"),
   "Ẩm thực cung đình Huế nổi tiếng với những món được tạo hình như hoa lá, chim muông, tượng trưng cho sự tinh tế của triều Nguyễn.",
   "Quán trong khu vực thành nội (quán mẫu)", 0, meal="dinner", desc="Bữa ăn theo thực đơn cung đình.", dishes=["Nem công chả phượng", "Cơm sen", "Chè sen"], aud=["cap_doi", "gia_dinh", "nhom_ban"], kids=False),
 place("cf-song-huong", "Quán cà phê ven sông Hương (mẫu)", "cafe", "afternoon", 16.4660, 107.5850, 75, 55000, "07:00", "22:00", "cafe",
   H("Ngồi ven sông, ngắm cầu Trường Tiền, hợp đi chiều", "Quán mẫu, chưa phải quán thật"),
   "Ngồi cà phê ven sông Hương là thói quen quen thuộc của người Huế vào chiều tối.",
   "Ven sông Hương (quán mẫu)", 0, desc="Quán cà phê ven sông.", dishes=["Cà phê", "Trà gừng", "Chè"]),
 place("cf-vuon-hue", "Cà phê vườn nhà rường (mẫu)", "cafe", "morning", 16.4610, 107.5750, 75, 60000, "07:00", "21:00", "cafe",
   H("Ngồi trong khu vườn nhà rường cổ, yên tĩnh", "Quán mẫu, chưa phải quán thật"),
   "Nhà rường là kiểu nhà gỗ truyền thống của Huế, nhiều quán cà phê giữ lại vườn và hiên gỗ để khách ngồi nghỉ.",
   "Phố trung tâm (quán mẫu)", 0, desc="Quán cà phê trong nhà rường.", dishes=["Cà phê", "Trà sen", "Bánh ngọt"]),
]
HOTELS = [
 ("hue-hostel", "hostel-bien", "Hostel gần phố Tây Huế (mẫu)", "Trung tâm", 200000, 16.4600, 107.5900, "Hostel nhỏ gần phố đi bộ, phù hợp đi tiết kiệm.", ["Wifi", "Bếp chung"]),
 ("hue-homestay", "homestay", "Homestay nhà rường (mẫu)", "Vỹ Dạ", 380000, 16.4560, 107.5990, "Homestay nhà rường cổ với vườn nhỏ, yên tĩnh.", ["Wifi", "Ăn sáng"]),
 ("hue-3sao", "3sao-tt", "Khách sạn 3 sao trung tâm (mẫu)", "Trung tâm", 650000, 16.4620, 107.5880, "Khách sạn 3 sao gần cầu Trường Tiền, đi bộ ra phố đêm.", ["Wifi", "Ăn sáng"]),
 ("hue-3sao-song", "3sao-bien", "Khách sạn 3 sao ven sông Hương (mẫu)", "Sông Hương", 800000, 16.4650, 107.5870, "Khách sạn 3 sao ven sông, phòng nhìn ra cầu Trường Tiền.", ["Wifi", "Ăn sáng", "Hồ bơi"]),
 ("hue-4sao", "4sao-tt", "Khách sạn 4 sao trung tâm (mẫu)", "Trung tâm", 1300000, 16.4640, 107.5900, "Khách sạn 4 sao có hồ bơi và nhà hàng, gần sông.", ["Wifi", "Ăn sáng", "Hồ bơi"]),
 ("hue-4sao-song", "4sao-bien", "Khách sạn 4 sao nhìn sông (mẫu)", "Sông Hương", 1550000, 16.4630, 107.5880, "Khách sạn 4 sao nhìn ra sông Hương và cầu Trường Tiền.", ["Wifi", "Ăn sáng", "Hồ bơi", "Spa"]),
 ("hue-resort", "resort-nhs", "Resort 5 sao vườn cố đô (mẫu)", "Ngoại thành", 3200000, 16.4300, 107.5600, "Resort 5 sao giữa vườn, kiến trúc kiểu cung đình, có spa và hồ bơi lớn.", ["Wifi", "Ăn sáng", "Hồ bơi", "Spa"]),
 ("hue-villa", "villa", "Villa vườn nhà rường (mẫu)", "Vỹ Dạ", 3800000, 16.4570, 107.6000, "Villa nguyên căn nhà vườn Huế, hợp gia đình đông người.", ["Wifi", "Ăn sáng", "Sân vườn", "Bếp"]),
]
run(CITY, NEW, HOTELS)
